import Head from "next/head";
import { Heebo, Inter, Source_Sans_3 } from "next/font/google";
import TopSection from "@/pages/TopSection";
import MiddleSection from "./MiddleSection";
import BottomSection from "./BottomSection";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const heebo = Heebo({ subsets: ["latin"], variable: "--font-heebo" });
const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${inter.variable} ${heebo.variable} ${sourceSans.variable}`}
      >
        <TopSection />
        <MiddleSection />
        <BottomSection />
      </main>
    </>
  );
}
