import Head from "next/head";

import Header from "@/pages/Header";
import TopSection from "@/pages/TopSection";
import MiddleSection from "@/pages/MiddleSection";
import FeaturesSection from "./FeaturesSection";
import Footer from "@/pages/Footer";

import localFont from "next/font/local";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blast landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${sf.className}`}>
        <Header />
        <TopSection />
        <MiddleSection />
        <FeaturesSection />
        {/* <BottomSection /> */}

        <Footer />
      </main>
    </>
  );
}

const sf = localFont({
  src: [
    {
      path: "./fonts/SFUIDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/SFUIDisplay-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SFUIDisplay-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/SFUIDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/SFUIDisplay-Heavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
});
